apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper-ha
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template: 
    metadata:
      labels:
        app: zookeeper
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - zookeeper
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: zookeeper
          image: "eduosi/zookeeper:latest"
          volumeMounts:
            - name: data
              mountPath: /data/zookeeper
          command:
            - "sh"
            - "-c"
            - "zookeeper \
              start \
              --servers=3 \
              --conf_dir=/usr/local/zookeeper/conf \
              --data_dir=/data/zookeeper/data \
              --data_log_dir=/data/zookeeper/log \
              --server_port=2888 \
              --client_port=2181 \
              --leader_election_port=3888 \
              --init_limit=10 \
              --tick_time=2000 \
              --sync_limit=5 \
              --max_client_cnxns=100 \
              --snap_retain_count=3 \
              --purge_interval=12 \
              --max_session_timeout=40000 \
              --min_session_timeout=4000 \
              --heap=256M \
              --log_level=ERROR"
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: server
            - containerPort: 3888
              name: leader-election
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
          livenessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: data
          hostPath:
            path: /data/zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-ha
  labels:
    name: zookeeper
spec:
  ports:
    - name: server
      protocol: "TCP"
      port: 2888
      targetPort: 2888
    - name: leader-election
      protocol: "TCP"
      port: 3888
      targetPort: 3888
  clusterIP: None
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    name: zookeeper
spec:
  ports:
    - name: client
      port: 2181
      targetPort: 2181
  selector:
    app: zookeeper
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zookeeper-pdb
spec:
  selector:
    matchLabels:
      app: zookeeper
  maxUnavailable: 1