version: '2'
services:
  kafka-node1:
    image: eduosi/kafka
    restart: always
    container_name: kafka-node1
    network_mode: bridge
    ports:
      - "19092:9092"
    environment:
      KAFKA_HEAP_OPTS: "-Xmx500M -Xmx500M"
      KAFKA_BROKER_ID: 201
      KAFKA_LISTENER_HOST: 0.0.0.0
      KAFKA_ADVERTISED_HOST: 172.16.52.1
      KAFKA_ADVERTISED_PORT: 19092
      KAFKA_SOCKET_SEND_BUFFER: 102400
      KAFKA_SOCKET_RECEIVE_BUFFER: 102400
      KAFKA_SOCKET_REQUEST_MAX: 524288000
      KAFKA_MESSAGE_MAX: 5242880
      KAFKA_REPLICA_FETCH_MAX: 5242880
      KAFKA_PARTITIONS_NUM: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_ZOOKEEPER: 172.16.52.1:12181,172.16.52.1:22181,172.16.52.1:32181
  kafka-node2:
    image: eduosi/kafka
    restart: always
    container_name: kafka-node2
    network_mode: bridge
    ports:
      - "29092:9092"
    environment:
      KAFKA_HEAP_OPTS: "-Xmx500M -Xmx500M"
      KAFKA_BROKER_ID: 202
      KAFKA_LISTENER_HOST: 0.0.0.0
      KAFKA_ADVERTISED_HOST: 172.16.52.1
      KAFKA_ADVERTISED_PORT: 29092
      KAFKA_SOCKET_SEND_BUFFER: 102400
      KAFKA_SOCKET_RECEIVE_BUFFER: 102400
      KAFKA_SOCKET_REQUEST_MAX: 524288000
      KAFKA_MESSAGE_MAX: 5242880
      KAFKA_REPLICA_FETCH_MAX: 5242880
      KAFKA_PARTITIONS_NUM: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_ZOOKEEPER: 172.16.52.1:12181,172.16.52.1:22181,172.16.52.1:32181
  kafka-node3:
    image: eduosi/kafka
    restart: always
    container_name: kafka-node3
    network_mode: bridge
    ports:
      - "39092:9092"
    environment:
      KAFKA_HEAP_OPTS: "-Xmx500M -Xmx500M"
      KAFKA_BROKER_ID: 203
      KAFKA_LISTENER_HOST: 0.0.0.0
      KAFKA_ADVERTISED_HOST: 172.16.52.1
      KAFKA_ADVERTISED_PORT: 39092
      KAFKA_SOCKET_SEND_BUFFER: 102400
      KAFKA_SOCKET_RECEIVE_BUFFER: 102400
      KAFKA_SOCKET_REQUEST_MAX: 524288000
      KAFKA_MESSAGE_MAX: 5242880
      KAFKA_REPLICA_FETCH_MAX: 5242880
      KAFKA_PARTITIONS_NUM: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_ZOOKEEPER: 172.16.52.1:12181,172.16.52.1:22181,172.16.52.1:32181