version: '2'
services:
  kafka-node1:
    image: eduosi/kafka
    restart: always
    container_name: kafka-node1
    network_mode: bridge
    ports:
      - "19092:9092"
    command: "kafka start \
              --host=0.0.0.0 \
              --port=9092 \
              --advertised_port=9092 \
              --network_threads=4 \
              --io_threads=4 \
              --socket_send_buffer=102400 \
              --socket_receive_buffer=102400 \
              --socket_request_max=104857600 \
              --message_max=5242880 \
              --replica_fetch_max=5242880 \
              --partitions_num=2 \
              --default_replication_factor=2 \
              --offsets_topic_replication_factor=2 \
              --transaction_state_log_replication_factor=2 \
              --log_flush_interval_messages=10000 \
              --log_flush_interval=1000 \
              --log_retention_hours=168 \
              --zookeeper=10.101.0.130:31518 \
              --zookeeper_connect_timeout=6000 \
              --log_level=INFO"
    environment:
      HOSTNAME: kafka-node-1
  kafka-node2:
    image: eduosi/kafka
    restart: always
    container_name: kafka-node2
    network_mode: bridge
    ports:
      - "29092:9092"
    command: "kafka start \
              --host=0.0.0.0 \
              --port=9092 \
              --advertised_port=9092 \
              --network_threads=4 \
              --io_threads=4 \
              --socket_send_buffer=102400 \
              --socket_receive_buffer=102400 \
              --socket_request_max=104857600 \
              --message_max=5242880 \
              --replica_fetch_max=5242880 \
              --partitions_num=2 \
              --default_replication_factor=2 \
              --offsets_topic_replication_factor=2 \
              --transaction_state_log_replication_factor=2 \
              --log_flush_interval_messages=10000 \
              --log_flush_interval=1000 \
              --log_retention_hours=168 \
              --zookeeper=10.101.0.130:31518 \
              --zookeeper_connect_timeout=6000 \
              --log_level=INFO"
    environment:
      HOSTNAME: kafka-node-2